//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTOG.TelegramSenderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TelegramSenderService.ITelegramSender")]
    public interface ITelegramSender {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegramSender/SendTelegram", ReplyAction="http://tempuri.org/ITelegramSender/SendTelegramResponse")]
        void SendTelegram(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITelegramSenderChannel : SampleTOG.TelegramSenderService.ITelegramSender, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TelegramSenderClient : System.ServiceModel.ClientBase<SampleTOG.TelegramSenderService.ITelegramSender>, SampleTOG.TelegramSenderService.ITelegramSender {
        
        public TelegramSenderClient() {
        }
        
        public TelegramSenderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TelegramSenderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelegramSenderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelegramSenderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendTelegram(string xml) {
            base.Channel.SendTelegram(xml);
        }
    }
}
